name: 'Maven Build'
description: 'Setup Java SDK and runs Maven build'
inputs:
  pom-file-path:
    description: "pom.xml file to use in mvn build command"
    required: false
    default: "./pom.xml"

runs:
  using: "composite"
  steps:
    - name: Build with Maven
      shell: bash
      id: maven-build
      run: |
        mvn clean install -f ${{ inputs.pom-file-path }}
