on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Publish version

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Git tag version
      shell: bash
      id: git-tag-version
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          git tag -a v1.0.${{ github.run_number }} -m "New actions release"
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git push origin --tags
        fi
